// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	users "domashka-backend/internal/entity/users"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockusersRepo is a mock of usersRepo interface.
type MockusersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockusersRepoMockRecorder
}

// MockusersRepoMockRecorder is the mock recorder for MockusersRepo.
type MockusersRepoMockRecorder struct {
	mock *MockusersRepo
}

// NewMockusersRepo creates a new mock instance.
func NewMockusersRepo(ctrl *gomock.Controller) *MockusersRepo {
	mock := &MockusersRepo{ctrl: ctrl}
	mock.recorder = &MockusersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockusersRepo) EXPECT() *MockusersRepoMockRecorder {
	return m.recorder
}

// CheckIfUserIsChef mocks base method.
func (m *MockusersRepo) CheckIfUserIsChef(ctx context.Context, userID int64) (*int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfUserIsChef", ctx, userID)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckIfUserIsChef indicates an expected call of CheckIfUserIsChef.
func (mr *MockusersRepoMockRecorder) CheckIfUserIsChef(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfUserIsChef", reflect.TypeOf((*MockusersRepo)(nil).CheckIfUserIsChef), ctx, userID)
}

// CreateWithPhone mocks base method.
func (m *MockusersRepo) CreateWithPhone(ctx context.Context, phone string) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithPhone", ctx, phone)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithPhone indicates an expected call of CreateWithPhone.
func (mr *MockusersRepoMockRecorder) CreateWithPhone(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithPhone", reflect.TypeOf((*MockusersRepo)(nil).CreateWithPhone), ctx, phone)
}

// GetByPhone mocks base method.
func (m *MockusersRepo) GetByPhone(ctx context.Context, phone string) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhone", ctx, phone)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhone indicates an expected call of GetByPhone.
func (mr *MockusersRepoMockRecorder) GetByPhone(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhone", reflect.TypeOf((*MockusersRepo)(nil).GetByPhone), ctx, phone)
}

// Update mocks base method.
func (m *MockusersRepo) Update(ctx context.Context, id int64, user users.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockusersRepoMockRecorder) Update(ctx, id, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockusersRepo)(nil).Update), ctx, id, user)
}

// MockredisClient is a mock of redisClient interface.
type MockredisClient struct {
	ctrl     *gomock.Controller
	recorder *MockredisClientMockRecorder
}

// MockredisClientMockRecorder is the mock recorder for MockredisClient.
type MockredisClientMockRecorder struct {
	mock *MockredisClient
}

// NewMockredisClient creates a new mock instance.
func NewMockredisClient(ctrl *gomock.Controller) *MockredisClient {
	mock := &MockredisClient{ctrl: ctrl}
	mock.recorder = &MockredisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockredisClient) EXPECT() *MockredisClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockredisClient) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockredisClientMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockredisClient)(nil).Get), key)
}

// IsExpired mocks base method.
func (m *MockredisClient) IsExpired(key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExpired", key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExpired indicates an expected call of IsExpired.
func (mr *MockredisClientMockRecorder) IsExpired(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExpired", reflect.TypeOf((*MockredisClient)(nil).IsExpired), key)
}

// Set mocks base method.
func (m *MockredisClient) Set(key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockredisClientMockRecorder) Set(key, value, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockredisClient)(nil).Set), key, value, ttl)
}

// MockjwtUsecase is a mock of jwtUsecase interface.
type MockjwtUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockjwtUsecaseMockRecorder
}

// MockjwtUsecaseMockRecorder is the mock recorder for MockjwtUsecase.
type MockjwtUsecaseMockRecorder struct {
	mock *MockjwtUsecase
}

// NewMockjwtUsecase creates a new mock instance.
func NewMockjwtUsecase(ctrl *gomock.Controller) *MockjwtUsecase {
	mock := &MockjwtUsecase{ctrl: ctrl}
	mock.recorder = &MockjwtUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjwtUsecase) EXPECT() *MockjwtUsecaseMockRecorder {
	return m.recorder
}

// GenerateJWT mocks base method.
func (m *MockjwtUsecase) GenerateJWT(userID int64, chefID *int64, role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJWT", userID, chefID, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJWT indicates an expected call of GenerateJWT.
func (mr *MockjwtUsecaseMockRecorder) GenerateJWT(userID, chefID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJWT", reflect.TypeOf((*MockjwtUsecase)(nil).GenerateJWT), userID, chefID, role)
}

// ValidateJWT mocks base method.
func (m *MockjwtUsecase) ValidateJWT(tokenString string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateJWT", tokenString)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateJWT indicates an expected call of ValidateJWT.
func (mr *MockjwtUsecaseMockRecorder) ValidateJWT(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateJWT", reflect.TypeOf((*MockjwtUsecase)(nil).ValidateJWT), tokenString)
}

// MockSMSClient is a mock of SMSClient interface.
type MockSMSClient struct {
	ctrl     *gomock.Controller
	recorder *MockSMSClientMockRecorder
}

// MockSMSClientMockRecorder is the mock recorder for MockSMSClient.
type MockSMSClientMockRecorder struct {
	mock *MockSMSClient
}

// NewMockSMSClient creates a new mock instance.
func NewMockSMSClient(ctrl *gomock.Controller) *MockSMSClient {
	mock := &MockSMSClient{ctrl: ctrl}
	mock.recorder = &MockSMSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSMSClient) EXPECT() *MockSMSClientMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSMSClient) Send(phone, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", phone, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSMSClientMockRecorder) Send(phone, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSMSClient)(nil).Send), phone, message)
}
