version: "3.8"

networks:
  domashka.local:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    networks:
      - domashka.local
    volumes:
      - ./logs:/app/logs
    ports:
      - "9093:9093"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=domashka
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
      - kafka
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - domashka.local
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=domashka
    restart: always

  redis:
    image: redis:7
    container_name: redis
    networks:
      - domashka.local
    ports:
      - "6379:6379"
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - domashka.local
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - domashka.local
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always

volumes:
  pgdata:
