FROM golang:1.23.3

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /dish_reviews_worker ./cmd/dish_reviews_worker

RUN chmod +x /dish_reviews_worker

CMD ["/dish_reviews_worker"]