// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cart/add_item": {
            "post": {
                "description": "Добавление товара в корзину",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Добавление товара в корзину",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddCartItemRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/cart/clear": {
            "post": {
                "description": "Очищение корзины",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Очищение корзины",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ClearCartRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/cart/create": {
            "post": {
                "description": "Создание корзины",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Создание корзины",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateCartRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/cart/remove_item": {
            "post": {
                "description": "Удаление товара из корзины",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Удаление товара из корзины",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RemoveCartItemRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/cart/update_item": {
            "post": {
                "description": "Обновление товара в корзине",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Обновление товара в корзине",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateCartItemRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/cart/{id}": {
            "get": {
                "description": "Получение корзины",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Получение корзины",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/cart/{id}/items": {
            "get": {
                "description": "Получение всех товаров в корзине",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Получение всех товаров в корзине",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/users/create": {
            "post": {
                "description": "Создание пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создание пользователя",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Получение пользователя по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получение пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "description": "Обновление данных пользователя по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Обновление пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Удаление пользователя по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Удаление пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "v1.AddCartItemRequest": {
            "type": "object",
            "properties": {
                "additional_ingredients_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "chef_id": {
                    "type": "string"
                },
                "customer_notes": {
                    "type": "string"
                },
                "dish_id": {
                    "type": "string"
                },
                "removed_ingredients_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "v1.ClearCartRequest": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "v1.CreateCartRequest": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "v1.CreateRequest": {
            "type": "object",
            "properties": {
                "alias": {
                    "description": "Полное имя (ФИО)",
                    "type": "string"
                },
                "birthday": {
                    "description": "День рождения (опционально)",
                    "type": "string"
                },
                "email": {
                    "description": "Электронная почта (опционально)",
                    "type": "string"
                },
                "external_id": {
                    "description": "Внешний ID (опционально)",
                    "type": "string"
                },
                "external_type": {
                    "description": "Внешний статус (0, 1, 2)",
                    "type": "integer"
                },
                "first_name": {
                    "description": "Имя",
                    "type": "string"
                },
                "last_name": {
                    "description": "Фамилия (опционально)",
                    "type": "string"
                },
                "notification_flag": {
                    "description": "Уведомления (0 = включены, 1 = выключены)",
                    "type": "integer"
                },
                "number_phone": {
                    "description": "Телефон (опционально)",
                    "type": "string"
                },
                "role": {
                    "description": "Роль (client, chef, admin)",
                    "type": "string"
                },
                "second_name": {
                    "description": "Отчество (опционально)",
                    "type": "string"
                },
                "status": {
                    "description": "Состояние (0 = не бан, 1 = бан)",
                    "type": "integer"
                },
                "telegram_name": {
                    "description": "Telegram username (опционально)",
                    "type": "string"
                },
                "username": {
                    "description": "Уникальный идентификатор",
                    "type": "string"
                }
            }
        },
        "v1.RemoveCartItemRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateCartItemRequest": {
            "type": "object",
            "properties": {
                "additional_ingredients_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "chef_id": {
                    "type": "string"
                },
                "customer_notes": {
                    "type": "string"
                },
                "dish_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "removed_ingredients_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateRequest": {
            "type": "object",
            "properties": {
                "alias": {
                    "description": "Полное имя (ФИО)",
                    "type": "string"
                },
                "birthday": {
                    "description": "День рождения (опционально)",
                    "type": "string"
                },
                "email": {
                    "description": "Электронная почта (опционально)",
                    "type": "string"
                },
                "external_id": {
                    "description": "Внешний ID (опционально)",
                    "type": "string"
                },
                "external_type": {
                    "description": "Внешний статус (0, 1, 2)",
                    "type": "integer"
                },
                "first_name": {
                    "description": "Имя",
                    "type": "string"
                },
                "last_name": {
                    "description": "Фамилия (опционально)",
                    "type": "string"
                },
                "notification_flag": {
                    "description": "Уведомления (0 = включены, 1 = выключены)",
                    "type": "integer"
                },
                "number_phone": {
                    "description": "Телефон (опционально)",
                    "type": "string"
                },
                "role": {
                    "description": "Роль (client, chef, admin)",
                    "type": "string"
                },
                "second_name": {
                    "description": "Отчество (опционально)",
                    "type": "string"
                },
                "status": {
                    "description": "Состояние (0 = не бан, 1 = бан)",
                    "type": "integer"
                },
                "telegram_name": {
                    "description": "Telegram username (опционально)",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9093",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Domashka",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
